const state={mode:'i2v',refVariant:'04',jobs:new Map(),modelTimer:null,historyMode:localStorage.getItem('h3HistoryMode')||'list',runtimeSeconds:null,runtimeTimer:null};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
const PODS_KEY='h3MobilePods';const ACTIVE_POD_KEY='h3MobileActivePodId';
function getPods(){try{const v=JSON.parse(localStorage.getItem(PODS_KEY)||'[]');return Array.isArray(v)?v:[];}catch{return [];}}
function savePods(pods){localStorage.setItem(PODS_KEY,JSON.stringify(pods));}
function getActivePod(){const id=localStorage.getItem(ACTIVE_POD_KEY);if(!id)return null;return getPods().find(p=>p.id===id)||null;}
function setActivePod(id){if(id)localStorage.setItem(ACTIVE_POD_KEY,id);else localStorage.removeItem(ACTIVE_POD_KEY);}
function apiUrl(path){const pod=getActivePod();if(!pod||!pod.baseUrl)return path;return pod.baseUrl.replace(/\/+$/,'')+path;}
function h3StatusClass(text){return {'準備中':'status-queued','待機中':'status-queued','実行中':'status-running','完了':'status-done','失敗':'status-failed'}[text]||'';}
function markJobCardFailed(card){if(!card)return;const status=card.querySelector('.job-status');if(status){status.textContent='失敗';status.className=`job-status ${h3StatusClass('失敗')}`.trim();}const el=card.querySelector('.elapsed');if(el)el.textContent='停止';}
function clearRefInput(id){const input=$('#'+id);if(!input)return;input.value='';delete input.dataset.serverName;input.dispatchEvent(new Event('change',{bubbles:true}));}
$$('.ref-clear').forEach(b=>b.onclick=()=>clearRefInput(b.dataset.target));
// 共通サムネイル表示: 通常のファイル選択(ネイティブchangeイベント)、
// media-library.jsのsetInputFile()(選択後にchangeイベントを発火させる)、
// 案件復元時のsetLocalInputFile()の直接呼び出し(下記)、すべてが同じ
// renderImagePreview()を通るため、選択経路によらず同じサムネイルが出る。
// 削除ボタン(clearRefInput)もchangeイベント経由でこの処理に合流するため、
// file inputクリアと同時にサムネイルも消える。
const PREVIEW_SLOTS=['image0','ref0','ref1','ref2'];
function renderImagePreview(input){
  if(!input)return;
  const img=$('#'+input.id+'preview');
  if(!img)return;
  const nameEl=$('#'+input.id+'filename');
  const box=input.closest('.ref-field');
  const f=input.files&&input.files[0];
  if(img.dataset.objectUrl){URL.revokeObjectURL(img.dataset.objectUrl);delete img.dataset.objectUrl;}
  if(f){
    const url=URL.createObjectURL(f);
    img.src=url;
    img.dataset.objectUrl=url;
    img.classList.remove('hidden');
    if(nameEl){nameEl.textContent=f.name;nameEl.classList.remove('hidden');}
    if(box)box.classList.add('has-thumb');
  }else{
    img.removeAttribute('src');
    img.classList.add('hidden');
    if(nameEl){nameEl.textContent='';nameEl.classList.add('hidden');}
    if(box)box.classList.remove('has-thumb');
  }
}
PREVIEW_SLOTS.forEach(id=>{const input=$('#'+id);if(input)input.addEventListener('change',()=>renderImagePreview(input));});
function defaultStepsForVariant(v){return v==='03'?4:14;}
function page(name){$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.target===name));$$('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===name));if(name==='settings'){loadModels();renderPods();}if(name==='history')loadHistory();}
$$('.nav').forEach(b=>b.onclick=()=>page(b.dataset.target));
function escapeHtml(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));}
function safeName(v){return String(v||'H3').replace(/[\\/:*?\"<>|]+/g,'_').slice(0,80);}
function randomSeed(){return Math.floor(Math.random()*999999999999999);}
function formatDuration(sec){sec=Math.max(0,Math.round(Number(sec)||0));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;if(h)return `${h}時間${String(m).padStart(2,'0')}分${String(s).padStart(2,'0')}秒`;if(m)return `${m}分${String(s).padStart(2,'0')}秒`;return `${s}秒`;}
function applyRefVariantDefaults(){if(state.mode!=='ref')return;if(state.refVariant==='03'){$('#steps').value=4;$('#modeNote').innerHTML='Ref2VA 03: <b>Turbo LoRA + TurboSampler + Sol-Attn(int8_qk) + FusedModulation</b> 固定。Steps / MPは変更できます。';}else{$('#steps').value=14;$('#modeNote').innerHTML='Ref2VA 04: <b>Sol-Attn(int8_qk) + BlockCache Balanced</b> 固定。Steps / MPは変更できます。';}}
function setRefVariant(v){state.refVariant=v;$$('#refVariant [data-variant]').forEach(b=>b.classList.toggle('active',b.dataset.variant===v));applyRefVariantDefaults();}
$$('#refVariant [data-variant]').forEach(b=>{if(!b.disabled)b.onclick=()=>{setRefVariant(b.dataset.variant);persistActiveProjectFields();};});
function setMode(mode){state.mode=mode;$$('[data-mode]').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));const ref=mode==='ref';$('#i2v').classList.toggle('hidden',ref);$('#ref').classList.toggle('hidden',!ref);$('#refextra').classList.toggle('hidden',!ref);$('#stepsWrap').classList.toggle('hidden',!ref);$('#ratio').disabled=!ref;if(ref){$('#ratio').value='3:4';$('#sec').value=6;applyRefVariantDefaults();}else{$('#ratio').value='元画像と同じ';$('#sec').value=10;$('#modeNote').innerHTML='I2V: <b>Turbo + Sage</b> / 4step固定。MPは変更できます。';}}
$$('[data-mode]').forEach(b=>b.onclick=()=>{setMode(b.dataset.mode);persistActiveProjectFields();});setMode('i2v');

// --- 案件（プロジェクト）ごとの独立状態管理 ---
// 固定URL側のlocalStorage(フィールド)/IndexedDB(参照画像の実バイナリ)にのみ保存し、
// RunPod側には一切保存しない。画像はFileオブジェクトをlocalStorageへ直接保存せず、
// 既存のお気に入り画像ライブラリ(media-library.js)と同じ「Blobを専用DBへ保存し、
// 復元時にFileを再構築する」方式を、専用のDB(h3-mobile-projects)で行う。
const PROJECTS_KEY='h3MobileProjects';const ACTIVE_PROJECT_KEY='h3MobileActiveProjectId';
const PROJECT_IMG_SLOTS=['image0','ref0','ref1','ref2'];
let suppressProjectPersist=false;
function getProjects(){try{const v=JSON.parse(localStorage.getItem(PROJECTS_KEY)||'[]');return Array.isArray(v)?v:[];}catch{return [];}}
function saveProjects(list){localStorage.setItem(PROJECTS_KEY,JSON.stringify(list));}
function getActiveProjectId(){return localStorage.getItem(ACTIVE_PROJECT_KEY)||null;}
function setActiveProjectId(id){if(id)localStorage.setItem(ACTIVE_PROJECT_KEY,id);else localStorage.removeItem(ACTIVE_PROJECT_KEY);}
function newProjectRecord(name){return {id:crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random(),name,title:name+' - テスト01',mode:'i2v',refVariant:'04',prompt:'',steps:null,seed:-1,sec:10,mp:0.5,ratio:'元画像と同じ',refSize:'max',images:{image0:null,ref0:null,ref1:null,ref2:null}};}
function ensureDefaultProjects(){if(getProjects().length)return;const list=['案件A','案件B','案件C'].map(newProjectRecord);saveProjects(list);setActiveProjectId(list[0].id);}
function openProjectImgDb(){return new Promise((res,rej)=>{const r=indexedDB.open('h3-mobile-projects',1);r.onupgradeneeded=()=>r.result.createObjectStore('images',{keyPath:'key'});r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
async function saveProjectImage(projectId,slot,file){const db=await openProjectImgDb();return new Promise((res,rej)=>{const tx=db.transaction('images','readwrite');tx.objectStore('images').put({key:`${projectId}::${slot}`,name:file.name,type:file.type,blob:file});tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error);});}
async function loadProjectImage(projectId,slot){const db=await openProjectImgDb();return new Promise((res,rej)=>{const r=db.transaction('images').objectStore('images').get(`${projectId}::${slot}`);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error);});}
async function deleteProjectImage(projectId,slot){const db=await openProjectImgDb();return new Promise((res,rej)=>{const tx=db.transaction('images','readwrite');tx.objectStore('images').delete(`${projectId}::${slot}`);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error);});}
function setLocalInputFile(input,file){const dt=new DataTransfer();dt.items.add(file);input.files=dt.files;renderImagePreview(input);}
function persistActiveProjectFields(){if(suppressProjectPersist)return;const id=getActiveProjectId();if(!id)return;const projects=getProjects();const idx=projects.findIndex(p=>p.id===id);if(idx<0)return;const p=projects[idx];p.mode=state.mode;p.refVariant=state.refVariant;p.title=$('#title').value;p.prompt=$('#prompt').value;if(state.mode==='ref')p.steps=Number($('#steps').value)||null;p.seed=Number($('#seed').value);p.sec=Number($('#sec').value);p.mp=Number($('#mp').value);p.ratio=$('#ratio').value;p.refSize=$('#refSize').value;projects[idx]=p;saveProjects(projects);}
async function persistProjectImageSlot(slot){if(suppressProjectPersist)return;const id=getActiveProjectId();if(!id)return;const input=$('#'+slot);if(!input)return;const projects=getProjects();const idx=projects.findIndex(p=>p.id===id);if(idx<0)return;const f=input.files[0];projects[idx].images=projects[idx].images||{};if(f){projects[idx].images[slot]={name:f.name,type:f.type};saveProjects(projects);try{await saveProjectImage(id,slot,f);}catch{}}else{projects[idx].images[slot]=null;saveProjects(projects);try{await deleteProjectImage(id,slot);}catch{}}}
PROJECT_IMG_SLOTS.forEach(slot=>{const input=$('#'+slot);if(input)input.addEventListener('change',()=>persistProjectImageSlot(slot));});
async function loadProjectIntoForm(id){const p=getProjects().find(x=>x.id===id);if(!p)return;suppressProjectPersist=true;try{setMode(p.mode||'i2v');setRefVariant(p.refVariant||'04');$('#title').value=p.title||'';$('#prompt').value=p.prompt||'';if(p.mode==='ref'){if(p.steps!=null)$('#steps').value=p.steps;$('#ratio').value=p.ratio||'3:4';}$('#sec').value=p.sec!=null?p.sec:(p.mode==='ref'?6:10);$('#mp').value=p.mp!=null?p.mp:0.5;$('#refSize').value=p.refSize||'max';$('#seed').value=p.seed!=null?p.seed:-1;for(const slot of PROJECT_IMG_SLOTS){const input=$('#'+slot);if(!input)continue;const meta=p.images&&p.images[slot];if(meta){try{const rec=await loadProjectImage(id,slot);if(rec&&rec.blob){const f=new File([rec.blob],rec.name||meta.name||'image.png',{type:rec.type||meta.type||'image/png'});setLocalInputFile(input,f);}else{input.value='';renderImagePreview(input);}}catch{input.value='';renderImagePreview(input);}}else{input.value='';renderImagePreview(input);}}if(typeof restoreBatchProjectState==='function')await restoreBatchProjectState(id);}finally{suppressProjectPersist=false;}}
function renderProjectTabs(){const tabs=$('#tabs');const addBtn=$('#add');if(!tabs||!addBtn)return;tabs.querySelectorAll('.pill:not(#add)').forEach(b=>b.remove());const projects=getProjects();const activeId=getActiveProjectId();for(const p of projects){const b=document.createElement('button');b.className='pill'+(p.id===activeId?' active':'');b.textContent=p.name;b.onclick=()=>switchProject(p.id);tabs.insertBefore(b,addBtn);}}
async function switchProject(id){if(id===getActiveProjectId())return;persistActiveProjectFields();setActiveProjectId(id);await loadProjectIntoForm(id);renderProjectTabs();}
async function initProjects(){ensureDefaultProjects();renderProjectTabs();const activeId=getActiveProjectId();if(activeId)await loadProjectIntoForm(activeId);}
['#title','#prompt','#sec','#mp','#ratio','#refSize','#seed','#steps'].forEach(s=>$(s)?.addEventListener('input',persistActiveProjectFields));
$('#add').onclick=async()=>{const n=prompt('案件名','案件D');if(!n)return;const rec=newProjectRecord(n);const projects=getProjects();projects.push(rec);saveProjects(projects);await switchProject(rec.id);};
$('#dup').onclick=()=>{$('#title').value+=' copy';persistActiveProjectFields();};
async function jsonFetch(url,opts){const r=await fetch(url,opts);if(!r.ok){let t='';try{t=await r.text();}catch{}throw new Error(t||`${r.status} ${r.statusText}`);}return r.json();}
async function health(){try{await jsonFetch(apiUrl('/h3-mobile/health'));await jsonFetch(apiUrl('/system_stats'));$('#status').textContent='ComfyUI 接続中';$('#connectNotice').className='notice ok';$('#connectNotice').textContent='ComfyUIへの接続は正常です。';}catch(e){$('#status').textContent='未接続';$('#connectNotice').className='notice danger';$('#connectNotice').textContent='ComfyUIへ接続できません。';}}
async function workflowStatus(){try{const [a,b,c]=await Promise.all([fetch(apiUrl('/h3-mobile/api/workflow/i2v')),fetch(apiUrl('/h3-mobile/api/workflow/ref2va_04')),fetch(apiUrl('/h3-mobile/api/workflow/ref2va_03'))]);if(!a.ok||!b.ok||!c.ok)throw new Error();$('#workflowStatus').className='notice ok';$('#workflowStatus').textContent='I2V / Ref2VA 03 / Ref2VA 04 API workflow 登録済み';}catch(e){$('#workflowStatus').className='notice danger';$('#workflowStatus').textContent='API workflowが不足しています。';}}
async function loadRuntime(){try{const data=await jsonFetch(apiUrl('/h3-mobile/api/runtime'));if(data.uptime_seconds==null)throw new Error();state.runtimeSeconds=Number(data.uptime_seconds);renderRuntime();if(!state.runtimeTimer)state.runtimeTimer=setInterval(()=>{if(state.runtimeSeconds!=null){state.runtimeSeconds++;renderRuntime();}},1000);}catch{$('#runtime').textContent='起動時間 --:--:--';}}
function renderRuntime(){if(state.runtimeSeconds==null)return;const sec=Math.max(0,Math.floor(state.runtimeSeconds));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;$('#runtime').textContent=`起動 ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
async function uploadImage(file){if(!file)throw new Error('画像を選択してください');const fd=new FormData();fd.append('image',file,file.name);fd.append('type','input');fd.append('overwrite','true');const data=await jsonFetch(apiUrl('/upload/image'),{method:'POST',body:fd});return data.name;}
function ratioApi(v){return {'2:3':'2:3 (Portrait Photo)','3:2':'3:2 (Landscape Photo)','9:16':'9:16 (Portrait)','16:9':'16:9 (Landscape)','1:1':'1:1 (Square)','4:3':'4:3 (Landscape Standard)','3:4':'3:4 (Portrait Standard)'}[v]||'3:4 (Portrait Standard)';}
function jobCard(title,mode,seconds,steps,ratio,mp,prompt,status='待機中'){const d=document.createElement('div');d.className='queue';d.innerHTML=`<div><b>${escapeHtml(title)}</b> <span class="badge">${mode}</span></div><div class="meta small"><span>${seconds}秒</span>${steps?`<span>${steps} steps</span>`:''}<span>${escapeHtml(ratio)}</span><span>${mp} MP</span><span class="job-status ${h3StatusClass(status)}">${status}</span><span class="elapsed">経過 0秒</span></div><details><summary>使用したプロンプトと設定を見る</summary><div class="small" style="margin-top:8px;line-height:1.7">${escapeHtml(prompt)}</div></details>`;return d;}
// 待機中は/prompt投入時刻(startedAt)基準の「待機 X」、実行中はtick()が
// /queueのqueue_runningで初めて確認した時刻(executionStartedAt)基準の
// 「経過 X」を表示する。完了/失敗はここでは更新しない(tick()が確定表示する)。
function updateJobTimers(){for(const job of state.jobs.values()){if(!job.card||!job.startedAt||job.done)continue;const el=job.card.querySelector('.elapsed');if(!el)continue;if(job.phase==='running'&&job.executionStartedAt){el.textContent=`経過 ${formatDuration((Date.now()-job.executionStartedAt)/1000)}`;}else{el.textContent=`待機 ${formatDuration((Date.now()-job.startedAt)/1000)}`;}}}
setInterval(updateJobTimers,1000);
async function buildAndQueue(){const title=$('#title').value||'無題';const prompt=$('#prompt').value.trim();if(!prompt)throw new Error('プロンプトを入力してください');const seconds=Math.max(1,Number($('#sec').value)||1);const megapixels=Math.min(2,Math.max(0.1,Number($('#mp').value)||0.5));$('#mp').value=String(megapixels);const isRef=state.mode==='ref';const steps=isRef?Math.max(1,Number($('#steps').value)||defaultStepsForVariant(state.refVariant)):null;const ratio=isRef?$('#ratio').value:'元画像と同じ';const card=jobCard(title,isRef?`Ref2VA ${state.refVariant}`:'I2V',seconds,steps,ratio,megapixels,prompt,'準備中');$('#queue').prepend(card);page('running');
try{
const wf=await jsonFetch(apiUrl(`/h3-mobile/api/workflow/${isRef?(state.refVariant==='03'?'ref2va_03':'ref2va_04'):'i2v'}`));let extra={title,mode:isRef?'ref2va':'i2v',variant:isRef?state.refVariant:null,prompt,seconds,steps,ratio,megapixels};if(isRef){const f0=$('#ref0').files[0],f1=$('#ref1').files[0],f2=$('#ref2').files[0];if(!f0)throw new Error('参照画像1を選択してください');const image0=await uploadImage(f0);wf['137'].inputs.image=image0;if(f1){const image1=await uploadImage(f1);wf['139'].inputs.image=image1;}else{delete wf['139'];delete wf['136'].inputs['ref_images.ref_image_1'];}if(f2){const image2=await uploadImage(f2);wf['h3mobile_ref3']={inputs:{image:image2},class_type:'LoadImage',_meta:{title:'参照画像3'}};wf['136'].inputs['ref_images.ref_image_2']=['h3mobile_ref3',0];extra.image2=image2;}else{delete wf['136'].inputs['ref_images.ref_image_2'];}wf['138'].inputs.value=prompt;wf['132'].inputs.value=seconds;wf['124'].inputs.steps=steps;wf['115'].inputs.aspect_ratio=ratioApi(ratio);wf['115'].inputs.megapixels=megapixels;const s=Number($('#seed').value);wf['129'].inputs.noise_seed=s===-1||!Number.isFinite(s)?randomSeed():s;wf['136'].inputs.ref_image_size=$('#refSize').value;wf['92'].inputs.filename_prefix='video/'+safeName(title);extra.seed=wf['129'].inputs.noise_seed;extra.ref_image_size=$('#refSize').value;extra.image0=image0;}else{const f=$('#image0').files[0];if(!f)throw new Error('元画像を選択してください');const image=await uploadImage(f);wf['114'].inputs.image=image;wf['119'].inputs.megapixels=megapixels;wf['105:104'].inputs.prompt=prompt;wf['105:111'].inputs.value=seconds;wf['105:15'].inputs.noise_seed=randomSeed();wf['92'].inputs.filename_prefix='video/'+safeName(title);extra.seed=wf['105:15'].inputs.noise_seed;extra.image0=image;}
const queued=await jsonFetch(apiUrl('/prompt'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:wf,extra_data:{h3_mobile:extra}})});card.querySelector('.meta').insertAdjacentHTML('beforeend',`<span>prompt_id: ${escapeHtml(queued.prompt_id)}</span>`);state.jobs.set(queued.prompt_id,{title,prompt,card,startedAt:Date.now(),phase:'queued'});return queued;
}catch(e){markJobCardFailed(card);throw e;}
}
$('#gen').onclick=async()=>{try{await buildAndQueue();}catch(e){const d=document.createElement('div');d.className='notice danger';d.textContent=e.message;$('#queue').prepend(d);page('running');}};
function historyExecutionSeconds(item){const messages=item?.status?.messages;if(!Array.isArray(messages))return null;let start=null,end=null;for(const msg of messages){if(!Array.isArray(msg)||msg.length<2)continue;const [type,data]=msg;const ts=Number(data?.timestamp);if(!Number.isFinite(ts))continue;if(type==='execution_start')start=ts;if(['execution_success','execution_error','execution_interrupted'].includes(type))end=ts;}return start!=null&&end!=null&&end>=start?(end-start)/1000:null;}
function setHistoryMode(mode){state.historyMode=mode==='large'?'large':'list';localStorage.setItem('h3HistoryMode',state.historyMode);$('#historyList').classList.toggle('large-view',state.historyMode==='large');$('#historyListMode').classList.toggle('active',state.historyMode==='list');$('#historyLargeMode').classList.toggle('active',state.historyMode==='large');}
$('#historyListMode').onclick=()=>setHistoryMode('list');$('#historyLargeMode').onclick=()=>setHistoryMode('large');
function openMedia(view,isVideo){const body=$('#modalBody');body.innerHTML=isVideo?`<video controls autoplay playsinline src="${view}"></video>`:`<img src="${view}" alt="output">`;$('#mediaModal').classList.remove('hidden');}
function closeMedia(){$('#mediaModal').classList.add('hidden');$('#modalBody').innerHTML='';}
$('#modalClose').onclick=closeMedia;$('#mediaModal').onclick=e=>{if(e.target===$('#mediaModal'))closeMedia();};
async function loadHistory(){const root=$('#historyList');root.className='history-list';setHistoryMode(state.historyMode);root.innerHTML='<div class="small" style="margin-top:12px">読込中...</div>';try{const data=await jsonFetch(apiUrl('/history'));const entries=Object.entries(data).reverse();root.innerHTML='';if(!entries.length){root.innerHTML='<div class="small" style="margin-top:12px">履歴はまだありません。</div>';return;}for(const [id,item] of entries.slice(0,50)){const extra=item?.prompt?.[3]?.h3_mobile||item?.prompt?.[3]?.extra_data?.h3_mobile||item?.prompt?.extra_data?.h3_mobile||item?.extra_data?.h3_mobile||{};const outputs=item.outputs||{};let media=null;for(const node of Object.values(outputs)){for(const key of ['videos','images','gifs','files']){if(Array.isArray(node?.[key])&&node[key][0]){media=node[key][0];break;}}if(media)break;}const card=document.createElement('div');card.className='history-card';const view=media?apiUrl(`/view?filename=${encodeURIComponent(media.filename)}&subfolder=${encodeURIComponent(media.subfolder||'')}&type=${encodeURIComponent(media.type||'output')}`):'';const isVideo=!!(view&&/\.(mp4|webm|mov|mkv)$/i.test(media.filename));const mediaHtml=view&&isVideo?`<video class="thumb history-media" muted playsinline preload="metadata" src="${view}"></video>`:view?`<img class="thumb history-media" src="${view}" alt="output">`:'<div class="thumb history-media-empty"></div>';const duration=historyExecutionSeconds(item);card.innerHTML=`<div class="thumbrow">${mediaHtml}<div class="history-content"><div><b>${escapeHtml(extra.title||id)}</b> <span class="badge">${escapeHtml(extra.mode||'ComfyUI')}</span>${extra.variant?`<span class="badge">${escapeHtml(extra.variant)}</span>`:''}</div><div class="meta small">${extra.seconds?`<span>${extra.seconds}秒動画</span>`:''}${extra.steps?`<span>${extra.steps} steps</span>`:''}${extra.ratio?`<span>${escapeHtml(extra.ratio)}</span>`:''}${extra.megapixels?`<span>${escapeHtml(extra.megapixels)} MP</span>`:''}${duration!=null?`<span class="duration-good">生成 ${formatDuration(duration)}</span>`:''}</div><details><summary>使用したプロンプトと設定を見る</summary><div class="small" style="margin-top:8px;line-height:1.7">${extra.prompt?escapeHtml(extra.prompt):'記録なし'}${extra.megapixels?`<br>解像度: ${escapeHtml(extra.megapixels)} MP`:''}${extra.seed!==undefined?`<br>Seed: ${escapeHtml(extra.seed)}`:''}${extra.ref_image_size?`<br>ref_image_size: ${escapeHtml(extra.ref_image_size)}`:''}</div></details>${view?`<div class="history-actions"><button class="secondary open-popup">開く</button><a class="secondary linkbtn" href="${view}" download>ダウンロード</a></div>`:''}</div></div>`;if(view){const mediaEl=card.querySelector('.history-media');if(mediaEl)mediaEl.onclick=()=>openMedia(view,isVideo);const openBtn=card.querySelector('.open-popup');if(openBtn)openBtn.onclick=()=>openMedia(view,isVideo);}root.appendChild(card);}}catch(e){root.innerHTML=`<div class="notice danger" style="margin-top:12px">履歴取得失敗: ${escapeHtml(e.message)}</div>`;}}
$('#refreshHistory').onclick=loadHistory;$('#refreshQueue').onclick=loadHistory;
$('#downloadAll').onclick=async()=>{const msg=$('#downloadMessage');msg.textContent='ZIPを作成しています。動画数が多い場合は少し待ちます。';try{const r=await fetch(apiUrl('/h3-mobile/api/history/download-all'));if(!r.ok){throw new Error(await r.text()||'一括ダウンロードに失敗しました');}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='h3-mobile-videos.zip';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);msg.textContent='一括ダウンロードを開始しました。';}catch(e){msg.textContent=`一括ダウンロード失敗: ${e.message}`;}};
function formatBytes(n){if(n==null)return 'サイズ取得中';const u=['B','KB','MB','GB','TB'];let i=0,v=Number(n);while(v>=1024&&i<u.length-1){v/=1024;i++;}return `${v.toFixed(i>=3?2:i>=2?1:0)} ${u[i]}`;}
function statusText(s){return ({missing:'未導入',queued:'待機中',downloading:'ダウンロード中',installed:'完了',error:'エラー',paused:'一時停止'})[s]||s;}
async function loadModels(){try{const data=await jsonFetch(apiUrl('/h3-mobile/api/models'));const root=$('#modelList');root.innerHTML='';let active=false;for(const m of Object.values(data.models)){const pct=m.total?Math.min(100,Math.round((m.downloaded||0)/m.total*100)):0;if(['queued','downloading'].includes(m.status))active=true;const item=document.createElement('div');item.className='model-item';item.innerHTML=`<div class="row"><div class="model-name">${escapeHtml(m.label)}</div><div class="model-status ${m.status==='installed'?'model-ok':m.status==='error'?'model-error':''}">${statusText(m.status)}</div></div><div class="small model-file">${escapeHtml(m.filename)}</div><div class="progress"><div class="progress-bar" style="width:${pct}%"></div></div><div class="row small"><span>${m.status==='downloading'||m.status==='queued'?`${formatBytes(m.downloaded||0)} / ${formatBytes(m.total)}`:m.status==='installed'?formatBytes(m.downloaded):''}</span><span class="grow"></span><span>${m.total?pct+'%':''}</span></div>${m.error?`<div class="small model-error-text">${escapeHtml(m.error)}</div>`:''}`;root.appendChild(item);}if(active&&!state.modelTimer)state.modelTimer=setInterval(loadModels,1500);if(!active&&state.modelTimer){clearInterval(state.modelTimer);state.modelTimer=null;}}catch(e){$('#modelList').innerHTML=`<div class="notice danger">モデル状態の取得に失敗: ${escapeHtml(e.message)}</div>`;}}
async function prepareModels(mode){const msg=$('#modelMessage');msg.className='notice';msg.textContent=mode==='ref2va'?'Ref2VA用モデルの準備を開始します。':'I2V用モデルの準備を開始します。';try{const data=await jsonFetch(apiUrl('/h3-mobile/api/models/prepare'),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode})});msg.className='notice ok';msg.textContent=data.started.length?`ダウンロード開始: ${data.started.length}件。RunPod側で続行します。`:'必要なモデルは準備済み、またはダウンロード中です。';loadModels();}catch(e){msg.className='notice danger';msg.textContent=`開始失敗: ${e.message}`;}}
$('#prepareRef').onclick=()=>prepareModels('ref2va');$('#prepareI2V').onclick=()=>prepareModels('i2v');
function reconnectPod(){health();workflowStatus();loadRuntime();loadHistory();loadModels();}
function renderPods(){const root=$('#podList');if(!root)return;const pods=getPods();const activeId=localStorage.getItem(ACTIVE_POD_KEY);root.innerHTML=pods.length?'':'<div class="small">登録されたPodはありません（未登録時はこのページの配信元へ直接接続します）。</div>';for(const pod of pods){const isActive=pod.id===activeId;const item=document.createElement('div');item.className='model-item';item.innerHTML=`<div class="row"><div class="model-name">${escapeHtml(pod.name)}</div>${isActive?'<div class="model-status model-ok">使用中</div>':''}</div><div class="small model-file">${escapeHtml(pod.baseUrl)}</div><div class="row small" style="margin-top:8px;gap:8px">${isActive?'':'<button class="secondary switch-pod" style="flex:1">切替</button>'}<button class="secondary del-pod" style="flex:1">削除</button></div>`;const switchBtn=item.querySelector('.switch-pod');if(switchBtn)switchBtn.onclick=()=>{setActivePod(pod.id);renderPods();reconnectPod();};item.querySelector('.del-pod').onclick=()=>{const remaining=getPods().filter(p=>p.id!==pod.id);savePods(remaining);if(isActive)setActivePod(remaining.length?remaining[0].id:null);renderPods();reconnectPod();};root.appendChild(item);}}
$('#addPod')?.addEventListener('click',()=>{const name=$('#newPodName').value.trim();let url=$('#newPodUrl').value.trim();if(!name||!url){$('#podMessage').textContent='Pod名とBase URLを入力してください。';return;}url=url.replace(/\/+$/,'');const pods=getPods();const pod={id:crypto.randomUUID?crypto.randomUUID():String(Date.now())+Math.random(),name,baseUrl:url};pods.push(pod);savePods(pods);if(!getActivePod())setActivePod(pod.id);$('#newPodName').value='';$('#newPodUrl').value='';$('#podMessage').textContent='Podを追加しました。';renderPods();reconnectPod();});
health();workflowStatus();loadRuntime();setHistoryMode(state.historyMode);loadHistory();loadModels();renderPods();initProjects();
