const state={mode:'i2v',jobs:new Map(),modelTimer:null};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function page(name){$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.target===name));$$('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===name));if(name==='settings')loadModels();}
$$('.nav').forEach(b=>b.onclick=()=>page(b.dataset.target));
$$('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;$$('[data-mode]').forEach(x=>x.classList.toggle('active',x===b));const ref=state.mode==='ref';$('#i2v').classList.toggle('hidden',ref);$('#ref').classList.toggle('hidden',!ref);$('#refextra').classList.toggle('hidden',!ref);$('#steps').value=ref?16:6;});
$$('#tabs .pill').forEach(b=>{if(b.id!=='add')b.onclick=()=>{$$('#tabs .pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#title').value=b.textContent+' - テスト01';};});
$('#add').onclick=()=>{const n=prompt('案件名','案件D');if(!n)return;const b=document.createElement('button');b.className='pill';b.textContent=n;$('#tabs').insertBefore(b,$('#add'));b.onclick=()=>{$$('#tabs .pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#title').value=n+' - テスト01';};};
$('#dup').onclick=()=>{$('#title').value+=' copy';};
async function jsonFetch(url,opts){const r=await fetch(url,opts);if(!r.ok){let t='';try{t=await r.text();}catch{}throw new Error(t||`${r.status} ${r.statusText}`);}return r.json();}
async function health(){try{await jsonFetch('/h3-mobile/health');await jsonFetch('/system_stats');$('#status').textContent='ComfyUI 接続中';$('#connectNotice').className='notice ok';$('#connectNotice').textContent='ComfyUIへの接続は正常です。';}catch(e){$('#status').textContent='未接続';$('#connectNotice').className='notice danger';$('#connectNotice').textContent='ComfyUIへ接続できません。';}}
async function workflowStatus(){try{const r=await fetch('/h3-mobile/api/ref2va-workflow');if(r.status===404){$('#workflowStatus').className='notice';$('#workflowStatus').textContent='Ref2VA API workflow はまだ未登録です。';return;}if(!r.ok)throw new Error();$('#workflowStatus').className='notice ok';$('#workflowStatus').textContent='Ref2VA API workflow 登録済み';}catch(e){$('#workflowStatus').className='notice danger';$('#workflowStatus').textContent='API workflow状態を確認できません。';}}
async function uploadImage(file){const fd=new FormData();fd.append('image',file,file.name);fd.append('overwrite','true');const data=await jsonFetch('/upload/image',{method:'POST',body:fd});return data.name;}
function jobCard(title,mode,seconds,steps,ratio,prompt,status='待機中'){const d=document.createElement('div');d.className='queue';d.innerHTML=`<div><b>${escapeHtml(title)}</b> <span class="badge">${mode}</span></div><div class="meta small"><span>${seconds}秒</span><span>${steps} steps</span><span>${ratio}</span><span>${status}</span></div><details><summary>使用したプロンプトと設定を見る</summary><div class="small" style="margin-top:8px;line-height:1.7">プロンプト: ${escapeHtml(prompt)}<br>Sampler: ${escapeHtml($('#sampler').value)}<br>Scheduler: ${escapeHtml($('#scheduler').value)}<br>Seed: ${escapeHtml($('#seed').value)}</div></details>`;return d;}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function formatBytes(n){if(n==null)return 'サイズ取得中';const u=['B','KB','MB','GB','TB'];let i=0,v=Number(n);while(v>=1024&&i<u.length-1){v/=1024;i++;}return `${v.toFixed(i>=3?2:i>=2?1:0)} ${u[i]}`;}
function statusText(s){return ({missing:'未導入',queued:'待機中',downloading:'ダウンロード中',installed:'完了',error:'エラー',paused:'一時停止'})[s]||s;}
async function loadModels(){try{const data=await jsonFetch('/h3-mobile/api/models');const root=$('#modelList');root.innerHTML='';let active=false;for(const m of Object.values(data.models)){const pct=m.total?Math.min(100,Math.round((m.downloaded||0)/m.total*100)):0;if(['queued','downloading'].includes(m.status))active=true;const item=document.createElement('div');item.className='model-item';item.innerHTML=`<div class="row"><div class="model-name">${escapeHtml(m.label)}</div><div class="model-status ${m.status==='installed'?'model-ok':m.status==='error'?'model-error':''}">${statusText(m.status)}</div></div><div class="small model-file">${escapeHtml(m.filename)}</div><div class="progress"><div class="progress-bar" style="width:${pct}%"></div></div><div class="row small"><span>${m.status==='downloading'||m.status==='queued'?`${formatBytes(m.downloaded||0)} / ${formatBytes(m.total)}`:m.status==='installed'?formatBytes(m.downloaded):''}</span><span class="grow"></span><span>${m.total?pct+'%':''}</span></div>${m.error?`<div class="small model-error-text">${escapeHtml(m.error)}</div>`:''}`;root.appendChild(item);}if(active&&!state.modelTimer)state.modelTimer=setInterval(loadModels,1500);if(!active&&state.modelTimer){clearInterval(state.modelTimer);state.modelTimer=null;}}catch(e){$('#modelList').innerHTML=`<div class="notice danger">モデル状態の取得に失敗: ${escapeHtml(e.message)}</div>`;}}
async function prepareModels(mode){const msg=$('#modelMessage');msg.className='notice';msg.textContent=mode==='ref2va'?'Ref2VA用モデルの準備を開始します。':'I2V用モデルの準備を開始します。';try{const data=await jsonFetch('/h3-mobile/api/models/prepare',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode})});msg.className='notice ok';msg.textContent=data.started.length?`ダウンロード開始: ${data.started.length}件。画面を閉じてもRunPod側で続行します。`:'必要なモデルはすでに準備済み、またはダウンロード中です。';loadModels();}catch(e){msg.className='notice danger';msg.textContent=`開始失敗: ${e.message}`;}}
$('#prepareRef').onclick=()=>prepareModels('ref2va');
$('#prepareI2V').onclick=()=>prepareModels('i2v');
$('#gen').onclick=async()=>{const title=$('#title').value||'無題';const prompt=$('#prompt').value;const seconds=Number($('#sec').value);const steps=Number($('#steps').value);const ratio=$('#ratio').value;const mode=state.mode==='ref'?'Ref2VA':'I2V';const card=jobCard(title,mode,seconds,steps,ratio,prompt,'準備中');$('#queue').prepend(card);page('running');if(state.mode!=='ref'){card.querySelector('.meta').insertAdjacentHTML('beforeend','<span>FL2VA API workflow未実装</span>');return;}try{const wfResp=await fetch('/h3-mobile/api/ref2va-workflow');if(!wfResp.ok)throw new Error('Ref2VA API workflow が未登録です');const workflow=await wfResp.json();const f0=$('#ref0').files[0],f1=$('#ref1').files[0];if(!f0)throw new Error('参照画像1を選択してください');const image0=await uploadImage(f0);const image1=f1?await uploadImage(f1):null;const payload={prompt:workflow,extra_data:{h3_mobile:{title,mode:'ref2va',prompt,seconds,steps,ratio,seed:Number($('#seed').value),ref_image_size:$('#refSize').value,image0,image1}}};const queued=await jsonFetch('/prompt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});card.querySelector('.meta').insertAdjacentHTML('beforeend',`<span>prompt_id: ${queued.prompt_id}</span>`);state.jobs.set(queued.prompt_id,{title,prompt});}catch(e){card.insertAdjacentHTML('beforeend',`<div class="notice danger" style="margin-top:10px">${escapeHtml(e.message)}</div>`);}};
async function loadHistory(){const root=$('#historyList');root.innerHTML='<div class="small" style="margin-top:12px">読込中...</div>';try{const data=await jsonFetch('/history');const entries=Object.entries(data).reverse();root.innerHTML='';if(!entries.length){root.innerHTML='<div class="small" style="margin-top:12px">履歴はまだありません。</div>';return;}for(const [id,item] of entries.slice(0,50)){const extra=item?.prompt?.[3]?.extra_data?.h3_mobile||item?.extra_data?.h3_mobile||{};const outputs=item.outputs||{};let media=null;for(const node of Object.values(outputs)){for(const key of ['videos','images','gifs']){if(Array.isArray(node?.[key])&&node[key][0]){media=node[key][0];break;}}if(media)break;}const card=document.createElement('div');card.className='history-card';const view=media?`/view?filename=${encodeURIComponent(media.filename)}&subfolder=${encodeURIComponent(media.subfolder||'')}&type=${encodeURIComponent(media.type||'output')}`:'';card.innerHTML=`<div class="thumbrow">${view?`<img class="thumb" src="${view}" alt="output">`:'<div class="thumb"></div>'}<div><div><b>${escapeHtml(extra.title||id)}</b></div><div class="meta small"><span>${escapeHtml(extra.mode||'ComfyUI')}</span>${extra.seconds?`<span>${extra.seconds}秒</span>`:''}${extra.steps?`<span>${extra.steps} steps</span>`:''}${extra.ratio?`<span>${escapeHtml(extra.ratio)}</span>`:''}</div><details><summary>使用したプロンプトと設定を見る</summary><div class="small" style="margin-top:8px;line-height:1.7">${extra.prompt?`プロンプト: ${escapeHtml(extra.prompt)}<br>`:''}Seed: ${extra.seed??'不明'}</div></details>${view?`<div class="history-actions"><a class="secondary linkbtn" href="${view}" target="_blank">開く</a><a class="secondary linkbtn" href="${view}" download>ダウンロード</a></div>`:''}</div></div>`;root.appendChild(card);}}catch(e){root.innerHTML=`<div class="notice danger" style="margin-top:12px">履歴取得失敗: ${escapeHtml(e.message)}</div>`;}}
$('#refreshHistory').onclick=loadHistory;
health();workflowStatus();loadHistory();loadModels();
