const state={mode:'i2v',jobs:new Map(),modelTimer:null,historyMode:localStorage.getItem('h3HistoryMode')||'list',runtimeSeconds:null,runtimeTimer:null};
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function page(name){$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.target===name));$$('.page').forEach(x=>x.classList.toggle('active',x.dataset.page===name));if(name==='settings')loadModels();if(name==='history')loadHistory();}
$$('.nav').forEach(b=>b.onclick=()=>page(b.dataset.target));
function escapeHtml(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));}
function safeName(v){return String(v||'H3').replace(/[\\/:*?\"<>|]+/g,'_').slice(0,80);}
function randomSeed(){return Math.floor(Math.random()*999999999999999);}
function formatDuration(sec){sec=Math.max(0,Math.round(Number(sec)||0));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;if(h)return `${h}時間${String(m).padStart(2,'0')}分${String(s).padStart(2,'0')}秒`;if(m)return `${m}分${String(s).padStart(2,'0')}秒`;return `${s}秒`;}
function setMode(mode){state.mode=mode;$$('[data-mode]').forEach(x=>x.classList.toggle('active',x.dataset.mode===mode));const ref=mode==='ref';$('#i2v').classList.toggle('hidden',ref);$('#ref').classList.toggle('hidden',!ref);$('#refextra').classList.toggle('hidden',!ref);$('#stepsWrap').classList.toggle('hidden',!ref);$('#ratio').disabled=!ref;if(ref){$('#steps').value=12;$('#ratio').value='3:4';$('#sec').value=6;$('#modeNote').innerHTML='Ref2VA: <b>Spectrum + Sol-Attn</b> 固定。Stepsは変更できます。';}else{$('#ratio').value='元画像と同じ';$('#sec').value=10;$('#modeNote').innerHTML='I2V: <b>Turbo + Sage</b> / 4step固定。Steps操作は不要です。';}}
$$('[data-mode]').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));setMode('i2v');
$$('#tabs .pill').forEach(b=>{if(b.id!=='add')b.onclick=()=>{$$('#tabs .pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#title').value=b.textContent+' - テスト01';};});
$('#add').onclick=()=>{const n=prompt('案件名','案件D');if(!n)return;const b=document.createElement('button');b.className='pill';b.textContent=n;$('#tabs').insertBefore(b,$('#add'));b.onclick=()=>{$$('#tabs .pill').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#title').value=n+' - テスト01';};};
$('#dup').onclick=()=>{$('#title').value+=' copy';};
async function jsonFetch(url,opts){const r=await fetch(url,opts);if(!r.ok){let t='';try{t=await r.text();}catch{}throw new Error(t||`${r.status} ${r.statusText}`);}return r.json();}
async function health(){try{await jsonFetch('/h3-mobile/health');await jsonFetch('/system_stats');$('#status').textContent='ComfyUI 接続中';$('#connectNotice').className='notice ok';$('#connectNotice').textContent='ComfyUIへの接続は正常です。';}catch(e){$('#status').textContent='未接続';$('#connectNotice').className='notice danger';$('#connectNotice').textContent='ComfyUIへ接続できません。';}}
async function workflowStatus(){try{const [a,b]=await Promise.all([fetch('/h3-mobile/api/workflow/i2v'),fetch('/h3-mobile/api/workflow/ref2va')]);if(!a.ok||!b.ok)throw new Error();$('#workflowStatus').className='notice ok';$('#workflowStatus').textContent='I2V / Ref2VA API workflow 登録済み';}catch(e){$('#workflowStatus').className='notice danger';$('#workflowStatus').textContent='API workflowが不足しています。';}}
async function loadRuntime(){try{const data=await jsonFetch('/h3-mobile/api/runtime');if(data.uptime_seconds==null)throw new Error();state.runtimeSeconds=Number(data.uptime_seconds);renderRuntime();if(!state.runtimeTimer)state.runtimeTimer=setInterval(()=>{if(state.runtimeSeconds!=null){state.runtimeSeconds++;renderRuntime();}},1000);}catch{$('#runtime').textContent='起動時間 --:--:--';}}
function renderRuntime(){if(state.runtimeSeconds==null)return;const sec=Math.max(0,Math.floor(state.runtimeSeconds));const h=Math.floor(sec/3600),m=Math.floor((sec%3600)/60),s=sec%60;$('#runtime').textContent=`起動 ${String(h).padStart(2,'0')}:${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`;}
async function uploadImage(file){if(!file)throw new Error('画像を選択してください');const fd=new FormData();fd.append('image',file,file.name);fd.append('type','input');fd.append('overwrite','true');const data=await jsonFetch('/upload/image',{method:'POST',body:fd});return data.name;}
function ratioApi(v){return {'2:3':'2:3 (Portrait Photo)','3:2':'3:2 (Landscape Photo)','9:16':'9:16 (Portrait)','16:9':'16:9 (Landscape)','1:1':'1:1 (Square)','4:3':'4:3 (Landscape Standard)','3:4':'3:4 (Portrait Standard)'}[v]||'3:4 (Portrait Standard)';}
function jobCard(title,mode,seconds,steps,ratio,prompt,status='待機中'){const d=document.createElement('div');d.className='queue';d.innerHTML=`<div><b>${escapeHtml(title)}</b> <span class="badge">${mode}</span></div><div class="meta small"><span>${seconds}秒</span>${steps?`<span>${steps} steps</span>`:''}<span>${escapeHtml(ratio)}</span><span>${status}</span><span class="elapsed">経過 0秒</span></div><details><summary>使用したプロンプトと設定を見る</summary><div class="small" style="margin-top:8px;line-height:1.7">${escapeHtml(prompt)}</div></details>`;return d;}
function updateJobTimers(){for(const job of state.jobs.values()){if(!job.card||!job.startedAt)continue;const el=job.card.querySelector('.elapsed');if(el)el.textContent=`経過 ${formatDuration((Date.now()-job.startedAt)/1000)}`;}}
setInterval(updateJobTimers,1000);
async function buildAndQueue(){const title=$('#title').value||'無題';const prompt=$('#prompt').value.trim();if(!prompt)throw new Error('プロンプトを入力してください');const seconds=Math.max(1,Number($('#sec').value)||1);const isRef=state.mode==='ref';const steps=isRef?Math.max(1,Number($('#steps').value)||12):null;const ratio=isRef?$('#ratio').value:'元画像と同じ';const card=jobCard(title,isRef?'Ref2VA':'I2V',seconds,steps,ratio,prompt,'準備中');$('#queue').prepend(card);page('running');const wf=await jsonFetch(`/h3-mobile/api/workflow/${isRef?'ref2va':'i2v'}`);let extra={title,mode:isRef?'ref2va':'i2v',prompt,seconds,steps,ratio};if(isRef){const f0=$('#ref0').files[0],f1=$('#ref1').files[0];if(!f0)throw new Error('参照画像1を選択してください');const image0=await uploadImage(f0);wf['137'].inputs.image=image0;if(f1){const image1=await uploadImage(f1);wf['139'].inputs.image=image1;}else{delete wf['139'];delete wf['136'].inputs['ref_images.ref_image_1'];}wf['138'].inputs.value=prompt;wf['132'].inputs.value=seconds;wf['124'].inputs.steps=steps;wf['115'].inputs.aspect_ratio=ratioApi(ratio);const s=Number($('#seed').value);wf['129'].inputs.noise_seed=s===-1||!Number.isFinite(s)?randomSeed():s;wf['136'].inputs.ref_image_size=$('#refSize').value;wf['92'].inputs.filename_prefix='video/'+safeName(title);extra.seed=wf['129'].inputs.noise_seed;extra.ref_image_size=$('#refSize').value;extra.image0=image0;}else{const f=$('#image0').files[0];if(!f)throw new Error('元画像を選択してください');const image=await uploadImage(f);wf['114'].inputs.image=image;wf['105:104'].inputs.prompt=prompt;wf['105:111'].inputs.value=seconds;wf['105:15'].inputs.noise_seed=randomSeed();wf['92'].inputs.filename_prefix='video/'+safeName(title);extra.seed=wf['105:15'].inputs.noise_seed;extra.image0=image;}
const queued=await jsonFetch('/prompt',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:wf,extra_data:{h3_mobile:extra}})});card.querySelector('.meta').insertAdjacentHTML('beforeend',`<span>prompt_id: ${escapeHtml(queued.prompt_id)}</span>`);state.jobs.set(queued.prompt_id,{title,prompt,card,startedAt:Date.now()});return queued;}
$('#gen').onclick=async()=>{try{await buildAndQueue();}catch(e){const d=document.createElement('div');d.className='notice danger';d.textContent=e.message;$('#queue').prepend(d);page('running');}};
function historyExecutionSeconds(item){const messages=item?.status?.messages;if(!Array.isArray(messages))return null;let start=null,end=null;for(const msg of messages){if(!Array.isArray(msg)||msg.length<2)continue;const [type,data]=msg;const ts=Number(data?.timestamp);if(!Number.isFinite(ts))continue;if(type==='execution_start')start=ts;if(['execution_success','execution_error','execution_interrupted'].includes(type))end=ts;}return start!=null&&end!=null&&end>=start?(end-start)/1000:null;}
function setHistoryMode(mode){state.historyMode=mode==='large'?'large':'list';localStorage.setItem('h3HistoryMode',state.historyMode);$('#historyList').classList.toggle('large-view',state.historyMode==='large');$('#historyListMode').classList.toggle('active',state.historyMode==='list');$('#historyLargeMode').classList.toggle('active',state.historyMode==='large');}
$('#historyListMode').onclick=()=>setHistoryMode('list');$('#historyLargeMode').onclick=()=>setHistoryMode('large');
function openMedia(view,isVideo){const body=$('#modalBody');body.innerHTML=isVideo?`<video controls autoplay playsinline src="${view}"></video>`:`<img src="${view}" alt="output">`;$('#mediaModal').classList.remove('hidden');}
function closeMedia(){$('#mediaModal').classList.add('hidden');$('#modalBody').innerHTML='';}
$('#modalClose').onclick=closeMedia;$('#mediaModal').onclick=e=>{if(e.target===$('#mediaModal'))closeMedia();};
async function loadHistory(){const root=$('#historyList');root.className='history-list';setHistoryMode(state.historyMode);root.innerHTML='<div class="small" style="margin-top:12px">読込中...</div>';try{const data=await jsonFetch('/history');const entries=Object.entries(data).reverse();root.innerHTML='';if(!entries.length){root.innerHTML='<div class="small" style="margin-top:12px">履歴はまだありません。</div>';return;}for(const [id,item] of entries.slice(0,50)){const extra=item?.prompt?.[3]?.extra_data?.h3_mobile||item?.prompt?.extra_data?.h3_mobile||item?.extra_data?.h3_mobile||{};const outputs=item.outputs||{};let media=null;for(const node of Object.values(outputs)){for(const key of ['videos','images','gifs','files']){if(Array.isArray(node?.[key])&&node[key][0]){media=node[key][0];break;}}if(media)break;}const card=document.createElement('div');card.className='history-card';const view=media?`/view?filename=${encodeURIComponent(media.filename)}&subfolder=${encodeURIComponent(media.subfolder||'')}&type=${encodeURIComponent(media.type||'output')}`:'';const isVideo=!!(view&&/\.(mp4|webm|mov|mkv)$/i.test(media.filename));const mediaHtml=view&&isVideo?`<video class="thumb history-media" muted playsinline preload="metadata" src="${view}"></video>`:view?`<img class="thumb history-media" src="${view}" alt="output">`:'<div class="thumb history-media-empty"></div>';const duration=historyExecutionSeconds(item);card.innerHTML=`<div class="thumbrow">${mediaHtml}<div class="history-content"><div><b>${escapeHtml(extra.title||id)}</b> <span class="badge">${escapeHtml(extra.mode||'ComfyUI')}</span></div><div class="meta small">${extra.seconds?`<span>${extra.seconds}秒動画</span>`:''}${extra.steps?`<span>${extra.steps} steps</span>`:''}${extra.ratio?`<span>${escapeHtml(extra.ratio)}</span>`:''}${duration!=null?`<span class="duration-good">生成 ${formatDuration(duration)}</span>`:''}</div><details><summary>使用したプロンプトと設定を見る</summary><div class="small" style="margin-top:8px;line-height:1.7">${extra.prompt?escapeHtml(extra.prompt):'記録なし'}${extra.seed!==undefined?`<br>Seed: ${escapeHtml(extra.seed)}`:''}</div></details>${view?`<div class="history-actions"><button class="secondary open-popup">開く</button><a class="secondary linkbtn" href="${view}" download>ダウンロード</a></div>`:''}</div></div>`;if(view){const mediaEl=card.querySelector('.history-media');if(mediaEl)mediaEl.onclick=()=>openMedia(view,isVideo);const openBtn=card.querySelector('.open-popup');if(openBtn)openBtn.onclick=()=>openMedia(view,isVideo);}root.appendChild(card);}}catch(e){root.innerHTML=`<div class="notice danger" style="margin-top:12px">履歴取得失敗: ${escapeHtml(e.message)}</div>`;}}
$('#refreshHistory').onclick=loadHistory;$('#refreshQueue').onclick=loadHistory;
$('#downloadAll').onclick=async()=>{const msg=$('#downloadMessage');msg.textContent='ZIPを作成しています。動画数が多い場合は少し待ちます。';try{const r=await fetch('/h3-mobile/api/history/download-all');if(!r.ok){throw new Error(await r.text()||'一括ダウンロードに失敗しました');}const blob=await r.blob();const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='h3-mobile-videos.zip';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),60000);msg.textContent='一括ダウンロードを開始しました。';}catch(e){msg.textContent=`一括ダウンロード失敗: ${e.message}`;}};
function formatBytes(n){if(n==null)return 'サイズ取得中';const u=['B','KB','MB','GB','TB'];let i=0,v=Number(n);while(v>=1024&&i<u.length-1){v/=1024;i++;}return `${v.toFixed(i>=3?2:i>=2?1:0)} ${u[i]}`;}
function statusText(s){return ({missing:'未導入',queued:'待機中',downloading:'ダウンロード中',installed:'完了',error:'エラー',paused:'一時停止'})[s]||s;}
async function loadModels(){try{const data=await jsonFetch('/h3-mobile/api/models');const root=$('#modelList');root.innerHTML='';let active=false;for(const m of Object.values(data.models)){const pct=m.total?Math.min(100,Math.round((m.downloaded||0)/m.total*100)):0;if(['queued','downloading'].includes(m.status))active=true;const item=document.createElement('div');item.className='model-item';item.innerHTML=`<div class="row"><div class="model-name">${escapeHtml(m.label)}</div><div class="model-status ${m.status==='installed'?'model-ok':m.status==='error'?'model-error':''}">${statusText(m.status)}</div></div><div class="small model-file">${escapeHtml(m.filename)}</div><div class="progress"><div class="progress-bar" style="width:${pct}%"></div></div><div class="row small"><span>${m.status==='downloading'||m.status==='queued'?`${formatBytes(m.downloaded||0)} / ${formatBytes(m.total)}`:m.status==='installed'?formatBytes(m.downloaded):''}</span><span class="grow"></span><span>${m.total?pct+'%':''}</span></div>${m.error?`<div class="small model-error-text">${escapeHtml(m.error)}</div>`:''}`;root.appendChild(item);}if(active&&!state.modelTimer)state.modelTimer=setInterval(loadModels,1500);if(!active&&state.modelTimer){clearInterval(state.modelTimer);state.modelTimer=null;}}catch(e){$('#modelList').innerHTML=`<div class="notice danger">モデル状態の取得に失敗: ${escapeHtml(e.message)}</div>`;}}
async function prepareModels(mode){const msg=$('#modelMessage');msg.className='notice';msg.textContent=mode==='ref2va'?'Ref2VA用モデルの準備を開始します。':'I2V用モデルの準備を開始します。';try{const data=await jsonFetch('/h3-mobile/api/models/prepare',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({mode})});msg.className='notice ok';msg.textContent=data.started.length?`ダウンロード開始: ${data.started.length}件。RunPod側で続行します。`:'必要なモデルは準備済み、またはダウンロード中です。';loadModels();}catch(e){msg.className='notice danger';msg.textContent=`開始失敗: ${e.message}`;}}
$('#prepareRef').onclick=()=>prepareModels('ref2va');$('#prepareI2V').onclick=()=>prepareModels('i2v');
health();workflowStatus();loadRuntime();setHistoryMode(state.historyMode);loadHistory();loadModels();
